CREATE TABLE UYELER(
  UYE_NO INT IDENTITY(1,1),
  UYE_ADI VARCHAR(30),
  UYE_SOYADI VARCHAR(20),
  CINSIYET VARCHAR(10),
  TELEFON VARCHAR(15),
  EPOSTA VARCHAR(50),
  ADRES_NO INT,
  PRIMARY KEY("UYE_NO")
  );

CREATE TABLE ADRESLER(
  ADRES_NO INT IDENTITY(1,1),
  CADDE VARCHAR(30),
  MAHALLE VARCHAR(30),
  BINA_NO INT,
  SEHIR VARCHAR(30),
  POSTA_KODU INT,
  ULKE VARCHAR(30),
  PRIMARY KEY("ADRES_NO")
  );

ALTER TABLE UYELER ADD CONSTRAINT "ADRESLER_UYELER"
FOREIGN KEY (ADRES_NO) REFERENCES ADRESLER(ADRES_NO);

CREATE TABLE EMANET(
  EMANET_NO INT IDENTITY(1,1),
  ISBN BIGINT NOT NULL,
  UYE_NO INT NOT NULL,
  KUTUPHANE_NO INT NOT NULL,
  EMANET_TARIHI DATETIME,
  TESLIM_TARIHI DATETIME,
  PRIMARY KEY("EMANET_NO")
  );

  CREATE TABLE KITAPLAR(
    ISBN VARCHAR(20),
	KITAP_ADI VARCHAR(30),
	YAYIN_TARIHI DATETIME,
	S_SAYISI INT,
	PRIMARY KEY("ISBN")
);

CREATE TABLE YAZARLAR(
	YAZAR_NO INT IDENTITY(1,1),
	YAZAR_ADI VARCHAR(20),
	YAZAR_SOYADI VARCHAR(20),
	PRIMARY KEY ("YAZAR_NO")
);

CREATE TABLE KATEGORILER(
	KATEGORI_NO INT IDENTITY(1,1),
	KATEGORI_ADI VARCHAR(20),
	PRIMARY KEY ("KATEGORI_NO")
);

CREATE TABLE KUTUPHANE(
	KUTUPHANE_NO INT IDENTITY(1,1),
	KUTUPHANE_ADI VARCHAR(20),
	ACIKLAMA VARCHAR(20),
	ADRES_NO INT,
	PRIMARY KEY ("KUTUPHANE_NO")
);

CREATE TABLE KITAP_KUTUPHANE(
	KUTUPHANE_NO INT NOT NULL,
	ISBN VARCHAR(20) NOT NULL,
	MIKTAR INT,
	CONSTRAINT "KITAP_KUTUPHANE_PK" PRIMARY KEY ("KUTUPHANE_NO", "ISBN"),
	CONSTRAINT "KITAP_KUTUPHANE_FK" FOREIGN KEY ("KUTUPHANE_NO") REFERENCES KATEGORILER(KATEGORI_NO)

);

ALTER TABLE KITAP_KUTUPHANE ADD CONSTRAINT "KITAP_KUTUPHANE_KITAPLAR_FK" FOREIGN KEY ("ISBN") REFERENCES KITAPLAR(ISBN);

CREATE TABLE KITAP_KATEGORI(
	ISBN VARCHAR(20) NOT NULL,
	KATEGORI_NO INT NOT NULL,
	CONSTRAINT "KITAP_KATEGORI_PK" PRIMARY KEY ("KATEGORI_NO", "ISBN")
);

CREATE TABLE KITAP_YAZAR(
	ISBN VARCHAR(20) NOT NULL,
	YAZAR_NO INT NOT NULL,
	CONSTRAINT "KITAP_YAZAR_PK" PRIMARY KEY ("YAZAR_NO", "ISBN")
);

